package mx.com.amis.sipac.invoice.persistence.domain;

public enum EstatusEnum {
  RECHAZO_COMITE_CONTROVERSIA("0"),
  REGISTRO_CONTROVERSIA("1"),
  ACEPTACION_MANUAL_CONTROVERSIA("2"),
  ACEPTACION_AUTOMATICA_CONTROVERSIA("3"),
  RECHAZO_CONTROVERSIA("4"),
  ACEPTACION_RECHAZO_MANUAL_CONTROVERSIA("5"),
  ACEPTACION_RECHAZO_AUTOMATICA_CONTROVERSIA("6"),
  REVOCACION_RECHAZO_CONTROVERSIA("7"),
  SEGUIMIENTO_COMITE_CONTROVERSIA("8"),
  ACEPTACION_COMITE_CONTROVERSIA("9"),
  ACEPTACIÓN_MANUAL("A"),
  ACEPTACIÓN_AUTOMÁTICA("B"),
  CONFIRMACIÓN_DE_ACEPTACIÓN_MANUAL("C"),
  CONFIRMACIÓN_DE_ACEPTACIÓN_AUTOMÁTICA("D"),
  CONFIRMACIÓN_ACEPTACIÓN_POR_COMITÉ("E"),
  CANCELACIÓN_CONFIRMACIÓN_DE_PAGO("J"),
  CANCELACIÓN_ACEPTACIÓN_PAGO("K"),
  ACLARACIÓN("L"),
  MODIFICADO("M"),
  ACEPTACIÓN_DE_RECHAZO("N"),
  CANCELACIÓN_REGISTRO("O"),
  PAGADO("P"),
  CONFIRMACIÓN_DE_PAGO("Q"),
  REGISTRADO("R"),
  ACEPTACIÓN_AUTOMÁTICA_POR_MATCH("S"),
  RECHAZO_MODIFICADO("U"),
  RECHAZO_REVOCADO("V"),
  CONFIRMACIO0N_RECHAZO_POR_COMITE("W"),
  RECHAZO_MANUAL("X"),
  CONFIRMACIÓN_DE_RECHAZO_MANUAL("Y"),
  CONFIRMACIÓN_DE_RECHAZO_AUTOMÁTICA("Z"),
  CONTROVERSIA_INVIERTE_RESPONSABLE("i"),
  CANCELACIÓN_CONTROVERSIA_TEMPORAL("o");
  
  private String estatusId; 
 
  private EstatusEnum(String estatusId) {
    this.estatusId = estatusId;
  }

  public String getEstatusId() {
    return this.estatusId;
  }
}