package mx.com.amis.sipac.invoice.persistence.domain;

public enum EstatusEnum {
  RECHAZO_COMITE_CONTROVERSIA("0"),
  REGISTRO_CONTROVERSIA("1"),
  ACEPTACION_MANUAL_CONTROVERSIA("2"),
  ACEPTACION_AUTOMATICA_CONTROVERSIA("3"),
  RECHAZO_CONTROVERSIA("4"),
  ACEPTACION_RECHAZO_MANUAL_CONTROVERSIA("5"),
  ACEPTACION_RECHAZO_AUTOMATICA_CONTROVERSIA("6"),
  REVOCACION_RECHAZO_CONTROVERSIA("7"),
  SEGUIMIENTO_COMITE_CONTROVERSIA("8"),
  ACEPTACION_COMITE_CONTROVERSIA("9"),
  ACEPTACION_MANUAL("A"),
  ACEPTACION_AUTOMATICA("B"),
  CONFIRMACION_DE_ACEPTACION_MANUAL("C"),
  CONFIRMACION_DE_ACEPTACION_AUTOMATICA("D"),
  CONFIRMACION_ACEPTACION_POR_COMITE("E"),
  CANCELACION_CONFIRMACION_DE_PAGO("J"),
  CANCELACION_ACEPTACION_PAGO("K"),
  ACLARACION("L"),
  MODIFICADO("M"),
  ACEPTACION_DE_RECHAZO("N"),
  CANCELACION_REGISTRO("O"),
  PAGADO("P"),
  CONFIRMACION_DE_PAGO("Q"),
  REGISTRADO("R"),
  ACEPTACION_AUTOMATICA_POR_MATCH("S"),
  RECHAZO_MODIFICADO("U"),
  RECHAZO_REVOCADO("V"),
  CONFIRMACIO0N_RECHAZO_POR_COMITE("W"),
  RECHAZO_MANUAL("X"),
  CONFIRMACION_DE_RECHAZO_MANUAL("Y"),
  CONFIRMACION_DE_RECHAZO_AUTOMATICA("Z"),
  CONTROVERSIA_INVIERTE_RESPONSABLE("i"),
  CANCELACION_CONTROVERSIA_TEMPORAL("o");
  
  private String estatusId; 
 
  private EstatusEnum(String estatusId) {
    this.estatusId = estatusId;
  }

  public String getEstatusId() {
    return this.estatusId;
  }
}