
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Cancelacion", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://go.reachcore.com/api/ws/timbre-fiscal/Cancelacion.svc/basic?wsdl")
public class Cancelacion
    extends Service
{

    private final static URL CANCELACION_WSDL_LOCATION;
    private final static WebServiceException CANCELACION_EXCEPTION;
    private final static QName CANCELACION_QNAME = new QName("http://tempuri.org/", "Cancelacion");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://go.reachcore.com/api/ws/timbre-fiscal/Cancelacion.svc/basic?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CANCELACION_WSDL_LOCATION = url;
        CANCELACION_EXCEPTION = e;
    }

    public Cancelacion() {
        super(__getWsdlLocation(), CANCELACION_QNAME);
    }

    public Cancelacion(WebServiceFeature... features) {
        super(__getWsdlLocation(), CANCELACION_QNAME, features);
    }

    public Cancelacion(URL wsdlLocation) {
        super(wsdlLocation, CANCELACION_QNAME);
    }

    public Cancelacion(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CANCELACION_QNAME, features);
    }

    public Cancelacion(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Cancelacion(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ICancelacion
     */
    @WebEndpoint(name = "BasicHttpBinding_ICancelacion")
    public ICancelacion getBasicHttpBindingICancelacion() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ICancelacion"), ICancelacion.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICancelacion
     */
    @WebEndpoint(name = "BasicHttpBinding_ICancelacion")
    public ICancelacion getBasicHttpBindingICancelacion(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ICancelacion"), ICancelacion.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CANCELACION_EXCEPTION!= null) {
            throw CANCELACION_EXCEPTION;
        }
        return CANCELACION_WSDL_LOCATION;
    }

}
