
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Emision", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://go.reachcore.com/api/ws/6.0/pacservices/Emision.svc/basic?wsdl")
public class Emision
    extends Service
{

    private final static URL EMISION_WSDL_LOCATION;
    private final static WebServiceException EMISION_EXCEPTION;
    private final static QName EMISION_QNAME = new QName("http://tempuri.org/", "Emision");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://go.reachcore.com/api/ws/6.0/pacservices/Emision.svc/basic?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMISION_WSDL_LOCATION = url;
        EMISION_EXCEPTION = e;
    }

    public Emision() {
        super(__getWsdlLocation(), EMISION_QNAME);
    }

    public Emision(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMISION_QNAME, features);
    }

    public Emision(URL wsdlLocation) {
        super(wsdlLocation, EMISION_QNAME);
    }

    public Emision(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMISION_QNAME, features);
    }

    public Emision(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Emision(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IEmision
     */
    @WebEndpoint(name = "BasicHttpBinding_IEmision")
    public IEmision getBasicHttpBindingIEmision() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IEmision"), IEmision.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEmision
     */
    @WebEndpoint(name = "BasicHttpBinding_IEmision")
    public IEmision getBasicHttpBindingIEmision(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IEmision"), IEmision.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMISION_EXCEPTION!= null) {
            throw EMISION_EXCEPTION;
        }
        return EMISION_WSDL_LOCATION;
    }

}
