
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import com.reachcore.services.api.ws.timbre_fiscal.cancelacion._2.CancelacionFiscalAsyncRequest;
import com.reachcore.services.api.ws.timbre_fiscal.cancelacion._2.CancelacionFiscalAsyncResponse;
import com.reachcore.services.api.ws.timbre_fiscal.cancelacion._2.CancelacionFiscalRequest;
import com.reachcore.services.api.ws.timbre_fiscal.cancelacion._2.CancelacionFiscalResponse;
import com.reachcore.services.api.ws.timbre_fiscal.cancelacion._2.FolioStatusRequest;
import com.reachcore.services.api.ws.timbre_fiscal.cancelacion._2.FolioStatusResponse;
import com.reachcore.services.api.ws.timbre_fiscal.cancelacion._2.TransactionStatusRequest;
import com.reachcore.services.api.ws.timbre_fiscal.cancelacion._2.TransactionStatusResponse;
import mx.gob.sat.cancelacfd.CancelaCFD;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ICancelacion", targetNamespace = "urn:reachcore.com:services:api:ws:timbre-fiscal:cancelacion:2.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    mx.gob.sat.cancelacfd.ObjectFactory.class,
    com.reachcore.cfdi.customheaders.ObjectFactory.class,
    com.reachcore.services.api.ws.timbre_fiscal.cancelacion._2.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class
})
public interface ICancelacion {


    /**
     * 
     * @param apiKey
     * @param parameters
     * @return
     *     returns com.reachcore.services.api.ws.timbre_fiscal.cancelacion._2.CancelacionFiscalResponse
     */
    @WebMethod(operationName = "Cancelar", action = "urn:reachcore.com:services:api:ws:timbre-fiscal:cancelacion:2.0/ICancelacion/Cancelar")
    @WebResult(name = "CancelacionFiscalResponse", targetNamespace = "urn:reachcore.com:services:api:ws:timbre-fiscal:cancelacion:2.0", partName = "parameters")
    @Action(input = "urn:reachcore.com:services:api:ws:timbre-fiscal:cancelacion:2.0/ICancelacion/Cancelar", output = "urn:reachcore.com:services:api:ws:timbre-fiscal:cancelacion:2.0/ICancelacion/CancelarResponse")
    public CancelacionFiscalResponse cancelar(
        @WebParam(name = "CancelacionFiscalRequest", targetNamespace = "urn:reachcore.com:services:api:ws:timbre-fiscal:cancelacion:2.0", partName = "parameters")
        CancelacionFiscalRequest parameters,
        @WebParam(name = "ApiKey", targetNamespace = "http://www.reachcore.com/CFDI/customHeaders", header = true, partName = "ApiKey")
        String apiKey);

    /**
     * 
     * @param apiKey
     * @param parameters
     * @return
     *     returns com.reachcore.services.api.ws.timbre_fiscal.cancelacion._2.CancelacionFiscalAsyncResponse
     */
    @WebMethod(operationName = "CancelarAsync", action = "urn:reachcore.com:services:api:ws:timbre-fiscal:cancelacion:2.0/ICancelacion/CancelarAsync")
    @WebResult(name = "CancelacionFiscalAsyncResponse", targetNamespace = "urn:reachcore.com:services:api:ws:timbre-fiscal:cancelacion:2.0", partName = "parameters")
    @Action(input = "urn:reachcore.com:services:api:ws:timbre-fiscal:cancelacion:2.0/ICancelacion/CancelarAsync", output = "urn:reachcore.com:services:api:ws:timbre-fiscal:cancelacion:2.0/ICancelacion/CancelarAsyncResponse")
    public CancelacionFiscalAsyncResponse cancelarAsync(
        @WebParam(name = "CancelacionFiscalAsyncRequest", targetNamespace = "urn:reachcore.com:services:api:ws:timbre-fiscal:cancelacion:2.0", partName = "parameters")
        CancelacionFiscalAsyncRequest parameters,
        @WebParam(name = "ApiKey", targetNamespace = "http://www.reachcore.com/CFDI/customHeaders", header = true, partName = "ApiKey")
        String apiKey);

    /**
     * 
     * @param apiKey
     * @param parameters
     * @return
     *     returns com.reachcore.services.api.ws.timbre_fiscal.cancelacion._2.TransactionStatusResponse
     */
    @WebMethod(operationName = "GetTransactionStatus", action = "urn:reachcore.com:services:api:ws:timbre-fiscal:cancelacion:2.0/ICancelacion/GetTransactionStatus")
    @WebResult(name = "TransactionStatusResponse", targetNamespace = "urn:reachcore.com:services:api:ws:timbre-fiscal:cancelacion:2.0", partName = "parameters")
    @Action(input = "urn:reachcore.com:services:api:ws:timbre-fiscal:cancelacion:2.0/ICancelacion/GetTransactionStatus", output = "urn:reachcore.com:services:api:ws:timbre-fiscal:cancelacion:2.0/ICancelacion/GetTransactionStatusResponse")
    public TransactionStatusResponse getTransactionStatus(
        @WebParam(name = "TransactionStatusRequest", targetNamespace = "urn:reachcore.com:services:api:ws:timbre-fiscal:cancelacion:2.0", partName = "parameters")
        TransactionStatusRequest parameters,
        @WebParam(name = "ApiKey", targetNamespace = "http://www.reachcore.com/CFDI/customHeaders", header = true, partName = "ApiKey")
        String apiKey);

    /**
     * 
     * @param apiKey
     * @param parameters
     * @return
     *     returns com.reachcore.services.api.ws.timbre_fiscal.cancelacion._2.FolioStatusResponse
     */
    @WebMethod(operationName = "GetFolioStatus", action = "urn:reachcore.com:services:api:ws:timbre-fiscal:cancelacion:2.0/ICancelacion/GetFolioStatus")
    @WebResult(name = "FolioStatusResponse", targetNamespace = "urn:reachcore.com:services:api:ws:timbre-fiscal:cancelacion:2.0", partName = "parameters")
    @Action(input = "urn:reachcore.com:services:api:ws:timbre-fiscal:cancelacion:2.0/ICancelacion/GetFolioStatus", output = "urn:reachcore.com:services:api:ws:timbre-fiscal:cancelacion:2.0/ICancelacion/GetFolioStatusResponse")
    public FolioStatusResponse getFolioStatus(
        @WebParam(name = "FolioStatusRequest", targetNamespace = "urn:reachcore.com:services:api:ws:timbre-fiscal:cancelacion:2.0", partName = "parameters")
        FolioStatusRequest parameters,
        @WebParam(name = "ApiKey", targetNamespace = "http://www.reachcore.com/CFDI/customHeaders", header = true, partName = "ApiKey")
        String apiKey);

    /**
     * 
     * @param apiKey
     * @param parameters
     * @return
     *     returns com.reachcore.services.api.ws.timbre_fiscal.cancelacion._2.CancelacionFiscalResponse
     */
    @WebMethod(operationName = "CancelarSolicitudFirmada", action = "urn:reachcore.com:services:api:ws:timbre-fiscal:cancelacion:2.0/ICancelacion/CancelarSolicitudFirmada")
    @WebResult(name = "CancelacionFiscalResponse", targetNamespace = "urn:reachcore.com:services:api:ws:timbre-fiscal:cancelacion:2.0", partName = "parameters")
    @Action(input = "urn:reachcore.com:services:api:ws:timbre-fiscal:cancelacion:2.0/ICancelacion/CancelarSolicitudFirmada", output = "urn:reachcore.com:services:api:ws:timbre-fiscal:cancelacion:2.0/ICancelacion/CancelarSolicitudFirmadaResponse")
    public CancelacionFiscalResponse cancelarSolicitudFirmada(
        @WebParam(name = "CancelaCFD", targetNamespace = "http://cancelacfd.sat.gob.mx", partName = "parameters")
        CancelaCFD parameters,
        @WebParam(name = "ApiKey", targetNamespace = "http://www.reachcore.com/CFDI/customHeaders", header = true, partName = "ApiKey")
        String apiKey);

}
