
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import com.reachcore.services.api.ws.pacservices._6.EmitirComprobanteRequest;
import com.reachcore.services.api.ws.pacservices._6.EmitirComprobanteResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IEmision", targetNamespace = "urn:reachcore.com:services:api:ws:pacservices:6.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.reachcore.cfdi.customheaders.ObjectFactory.class,
    com.reachcore.services.api.ws.pacservices._6.ObjectFactory.class
})
public interface IEmision {


    /**
     * 
     * @param apiKey
     * @param parameters
     * @return
     *     returns com.reachcore.services.api.ws.pacservices._6.EmitirComprobanteResponse
     */
    @WebMethod(operationName = "EmitirComprobante", action = "urn:reachcore.com:services:api:ws:pacservices:6.0/IEmision/EmitirComprobante")
    @WebResult(name = "EmitirComprobanteResponse", targetNamespace = "urn:reachcore.com:services:api:ws:pacservices:6.0", partName = "parameters")
    @Action(input = "urn:reachcore.com:services:api:ws:pacservices:6.0/IEmision/EmitirComprobante", output = "urn:reachcore.com:services:api:ws:pacservices:6.0/IEmision/EmitirComprobanteResponse")
    public EmitirComprobanteResponse emitirComprobante(
        @WebParam(name = "EmitirComprobanteRequest", targetNamespace = "urn:reachcore.com:services:api:ws:pacservices:6.0", partName = "parameters")
        EmitirComprobanteRequest parameters,
        @WebParam(name = "ApiKey", targetNamespace = "http://www.reachcore.com/CFDI/customHeaders", header = true, partName = "ApiKey")
        String apiKey);

}
