INSERT INTO FAC_ESTATUS_FACTURACION (ID_ESTATUS_FACTURACION,DESCRIPCION,ACTIVO) VALUES (1,'EN_PROCESO',1);
INSERT INTO FAC_ESTATUS_FACTURACION (ID_ESTATUS_FACTURACION,DESCRIPCION,ACTIVO) VALUES (2,'FACTURA',1);
INSERT INTO FAC_ESTATUS_FACTURACION (ID_ESTATUS_FACTURACION,DESCRIPCION,ACTIVO) VALUES (3,'NOTA_CREDITO',1);
INSERT INTO FAC_ESTATUS_FACTURACION (ID_ESTATUS_FACTURACION,DESCRIPCION,ACTIVO) VALUES (4,'COMPLEMENTO',1);
INSERT INTO FAC_ESTATUS_FACTURACION (ID_ESTATUS_FACTURACION,DESCRIPCION,ACTIVO) VALUES (5,'CANCELACION',1);

