CREATE OR REPLACE VIEW V_FAC_BITACORA_OPS
AS
select 
	U.ID_USUARIO_BITACORA,
	B.NOMBRE_USUARIO,
	B.APELLIDO_PATERNO,
	B.APELLIDO_MATERNO,
	'FAC_USUARIO' AS CATALOGO,
	'Actualizado' AS OPERACION,
	'Operacion Aplicada' AS ESTATUS,
	U.FECHA_REGISTRO AS FECHA_DE_OPERACION,
	U.NOMBRE_USUARIO AS REGISTRO_AFECTADO,
	C.NOMBRE AS COMPANIA
FROM FAC_USUARIO_BITACORA U
LEFT OUTER JOIN COMPANIAS C ON U.ID_COMPANIA = C.CIA_ID
LEFT OUTER JOIN FAC_USUARIO B ON U.ID_USUARIO_REGISTRO = B.ID_USUARIO;

CREATE OR REPLACE VIEW V_FAC_COMPANIA_APIKEY_LOG
AS
Select 
	A.ID_COMPANIA_APIKEY
	,A.APIKEY
	,A.ACTIVO
	,C.NOMBRE AS COMPANIA
	,A.FECHA_INICIO
	,A.FECHA_FIN
	,A.FECHA_REGISTRO
	,B.NOMBRE AS USUARIO_REGISTRO
FROM 
	FAC_COMPANIA_APIKEY A
LEFT OUTER JOIN COMPANIAS C ON A.COMPANIA_ID = C.CIA_ID	
LEFT OUTER JOIN FAC_USUARIO B ON A.ID_USUARIO_REGISTRO = B.ID_USUARIO;

CREATE OR REPLACE VIEW V_FAC_PR
AS
SELECT DISTINCT
	C.ID_ORDEN_FACTURADA as [FACTURADA_ID]
	,'D' as [TYPE]
	,A.TIPO_CAPTURA as CAPTURA
	,A.FOLIO_ORDEN as [FOLIO_ORDEN]
	,B.SINIESTRO_DEUDOR as [SIN_DEUDOR]
--	,B.POLIZA as [POLIZA_DEUDOR]
	,A.SINIESTRO_ACREEDOR as [SIN_ACREEDORA]
--    ,A.POLIZA_ACREEDOR as [POLIZA_ACRREDORA]
	,A.SINIESTRO_CORRECTO as [CORRECT_EVENT]
	
,(SELECT SUM(SA.IMPORTE_SANCION)
                        FROM dbo.FAC_ORDEN_FACTURADA C1
						LEFT OUTER JOIN dbo.SANCIONES SA on C1.ID_SINIESTRO = SA.SINIESTRO_ID and C1.FOLIO = SA.FOLIO_ORDEN and SA.TIPO_ORDEN = 'D'
						where C1.ID_ORDEN_FACTURADA = C.ID_ORDEN_FACTURADA
						group by C1.ID_SINIESTRO,C1.FOLIO) as [SANCION]
	,A.DIAS_TRANSC as DAYS
	,A.FECHA_CAPTURA as REGISTRO
	,A.FECHA_EXP as EXPEDITION
	,B.FECHA_SINIESTRO as EVENT_FOLIO
	,E.DESCRIPCION as STATE
	,M.DESCRIPCION as LOCATION
	,CASE
	
		WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then 'CANCELACION'
		WHEN ISNULL(FM2.FECHA_MOVIMIENTO,'') <> '' then 'NOTA_CREDITO'
		WHEN ISNULL(FM3.FECHA_MOVIMIENTO,'') <> '' then 'COMPLEMENTO'
		WHEN ISNULL(FM1.FECHA_MOVIMIENTO,'') <> '' then 'FACTURA'
		/*WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO
		WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO*/
		
		End as [ULTIMO_STATUS]
	,CASE
		WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO
		WHEN ISNULL(FM2.FECHA_MOVIMIENTO,'') <> '' then FM2.FECHA_MOVIMIENTO
		WHEN ISNULL(FM3.FECHA_MOVIMIENTO,'') <> '' then FM3.FECHA_MOVIMIENTO
		WHEN ISNULL(FM1.FECHA_MOVIMIENTO,'') <> '' then FM1.FECHA_MOVIMIENTO
		/*WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO
		WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO*/
		
		End as [FECHA_ESTATUS]
	
	,A.OBSERVACIONES as CREDITOR_OBSERVATION
	,B.OBSERVACIONES as DEBITOR_OBSERVATION
	,A.OBS_COMITE as COMITE_OBSERVATION
	,B.CIRCUNSTANCIA_ID_DEU as DEBITOR_CIRCUMSTANCES
	,A.CIRCUNSTANCIA_ID_ACR as CREDITOR_CIRCUMSTANCES
	,TD.TTRANS_DESC as DEBITOR_TOT
	,TA.TTRANS_DESC as CREDITOR_TOT
	,TA.TTRANS_DESC as BASE
	,FM1.UUID as [FRACTURA_FOLIO]
	,FM2.UUID as [COMPLEMENTO_FOLIO]
	,FM3.UUID as [CANCELADA_FOLIO]
	,FM4.UUID as [CREDITO_FOLIO]
	,FM1.FECHA_MOVIMIENTO as [FECHA_FACTURA]
	,FE.FECHA_PAGO as [FECHA_PAGO]
	,FM2.FECHA_MOVIMIENTO as [FECHA_COMPLEMENTO_DE_PAGOS]
	,FM3.FECHA_MOVIMIENTO as [FECHA_CANCELADA]
	,FM4.FECHA_MOVIMIENTO as [FECHA_NOTA_DE_CREDITO]
	,FE.FECHA_ACEPTACION as ACEPTACION
	,FM2.FECHA_MOVIMIENTO as PAYMENT_DATE
	,FE.FECHA_PRIMER_RECHAZO as FIRST_REJECTION_DATE
	,A.IMPORTE_SALDO as COSTO
	,MR.DESCRIPCION  as MOTIVO
	,(SELECT 
		U.NOMBRE || ' ' || U.AP_PATERNO || ' ' || U.AP_MATERNO 
		FROM dbo.ORDENES_DANO_MATERIAL A1
		LEFT OUTER JOIN USUARIOS U on A1.USUARIO_ID = U.USUARIO_ID 
		WHERE A1.FOLIO_ORDEN = A.FOLIO_ORDEN and A1.SINIESTRO_ID = A.SINIESTRO_ID )as CAPTURED_BY
	,(SELECT 
		U.NOMBRE || ' ' || U.AP_PATERNO || ' ' || U.AP_MATERNO 
		FROM dbo.ORDENES_DANO_MATERIAL A1
		LEFT OUTER JOIN USUARIOS U on A1.USUARIO_ID = U.USUARIO_ID 
		WHERE A1.FOLIO_ORDEN = A.FOLIO_ORDEN and A1.SINIESTRO_ID = A.SINIESTRO_ID ) as MODIFIED_BY
	,X.NOMBRE as [DEUDORA]
	,Y.NOMBRE as [ACREEDORA]
from dbo.ORDENES_DANO_MATERIAL A
LEFT OUTER JOIN dbo.SINIESTROS B on A.SINIESTRO_ID = B.SINIESTRO_ID
LEFT OUTER JOIN dbo.MUNICIPIOS M on B.MUNICIPIO_ID = M.MUNICIPIO_ID
LEFT OUTER JOIN dbo.ESTADOS E on M.ESTADO_ID = E.ESTADO_ID
LEFT OUTER JOIN dbo.V_TRANS_MAR_TIPO TD on B.TIPO_ID = TD.TIPO_ID
LEFT OUTER JOIN dbo.V_TRANS_MAR_TIPO TA on A.TIPO_ID = TA.TIPO_ID
INNER JOIN dbo.FAC_ORDEN_FACTURADA C on A.FOLIO_ORDEN = C.FOLIO and A.SINIESTRO_ID = C.ID_SINIESTRO and C.TIPO_ORDEN = 'D'
LEFT OUTER JOIN dbo.V_BIT_ORD_DM_FECHAS FE on C.FOLIO = FE.FOLIO_ORDEN and C.ID_SINIESTRO = FE.SINIESTRO_ID
LEFT OUTER JOIN dbo.FAC_MOVIMIENTO_FACTURACION D on C.ID_ORDEN_FACTURADA = D.ID_ORDEN_FACTURADA
LEFT OUTER JOIN COMPANIAS X ON B.CIA_DEUDORA = X.CIA_ID
LEFT OUTER JOIN COMPANIAS Y ON A.CIA_ACREEDORA = Y.CIA_ID	
LEFT OUTER JOIN V_FAC_REPORT_STATUS VFM1 on A.SINIESTRO_ID = VFM1.SINIESTRO_ID and A.FOLIO_ORDEN = VFM1.FOLIO_ORDEN and VFM1.Status = 2
LEFT OUTER JOIN FAC_MOVIMIENTO_FACTURACION FM1 on VFM1.MomentoID = FM1.ID_MOVIMIENTO_FACTURACION 
LEFT OUTER JOIN V_FAC_REPORT_STATUS VFM2 on A.SINIESTRO_ID = VFM2.SINIESTRO_ID and A.FOLIO_ORDEN = VFM2.FOLIO_ORDEN and VFM2.Status = 3
LEFT OUTER JOIN FAC_MOVIMIENTO_FACTURACION FM2 on VFM2.MomentoID = FM2.ID_MOVIMIENTO_FACTURACION 
LEFT OUTER JOIN V_FAC_REPORT_STATUS VFM3 on A.SINIESTRO_ID = VFM3.SINIESTRO_ID and A.FOLIO_ORDEN = VFM3.FOLIO_ORDEN and VFM3.Status = 4
LEFT OUTER JOIN FAC_MOVIMIENTO_FACTURACION FM3 on VFM3.MomentoID = FM3.ID_MOVIMIENTO_FACTURACION 
LEFT OUTER JOIN V_FAC_REPORT_STATUS VFM4 on A.SINIESTRO_ID = VFM4.SINIESTRO_ID and A.FOLIO_ORDEN = VFM4.FOLIO_ORDEN and VFM4.Status = 5
LEFT OUTER JOIN FAC_MOVIMIENTO_FACTURACION FM4 on VFM4.MomentoID = FM4.ID_MOVIMIENTO_FACTURACION
LEFT OUTER JOIN MOTIVO_RECHAZO MR on A.MOTIVO_ID = MR.MOTIVO_ID
UNION
SELECT DISTINCT
	C.ID_ORDEN_FACTURADA as [FACTURADA_ID]
	,'D' as [TYPE]
	,A.TIPO_CAPTURA as CAPTURA
	,A.FOLIO_ORDEN as [FOLIO_ORDEN]
	,B.SINIESTRO_DEUDOR as [SIN_DEUDOR]
--	,B.POLIZA as [POLIZA_DEUDOR]
	,A.SINIESTRO_ACREEDOR as [SIN_ACREEDORA]
--    ,A.POLIZA_ACREEDOR as [POLIZA_ACRREDORA]
	,A.SINIESTRO_CORRECTO as [CORRECT_EVENT]
	
,(SELECT SUM(SA.IMPORTE_SANCION)
                        FROM dbo.FAC_ORDEN_FACTURADA C1
						LEFT OUTER JOIN dbo.SANCIONES SA on C1.ID_SINIESTRO = SA.SINIESTRO_ID and C1.FOLIO = SA.FOLIO_ORDEN and SA.TIPO_ORDEN = 'D'
						where C1.ID_ORDEN_FACTURADA = C.ID_ORDEN_FACTURADA
						group by C1.ID_SINIESTRO,C1.FOLIO) as [SANCION]
	,A.DIAS_TRANSC as DAYS
	,A.FECHA_CAPTURA as REGISTRO
	,A.FECHA_EXP as EXPEDITION
	,B.FECHA_SINIESTRO as EVENT_FOLIO
	,E.DESCRIPCION as STATE
	,M.DESCRIPCION as LOCATION
	,CASE
	
		WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then 'CANCELACION'
		WHEN ISNULL(FM2.FECHA_MOVIMIENTO,'') <> '' then 'NOTA_CREDITO'
		WHEN ISNULL(FM3.FECHA_MOVIMIENTO,'') <> '' then 'COMPLEMENTO'
		WHEN ISNULL(FM1.FECHA_MOVIMIENTO,'') <> '' then 'FACTURA'
		/*WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO
		WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO*/
		
		End as [ULTIMO_STATUS]
	,CASE
		WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO
		WHEN ISNULL(FM2.FECHA_MOVIMIENTO,'') <> '' then FM2.FECHA_MOVIMIENTO
		WHEN ISNULL(FM3.FECHA_MOVIMIENTO,'') <> '' then FM3.FECHA_MOVIMIENTO
		WHEN ISNULL(FM1.FECHA_MOVIMIENTO,'') <> '' then FM1.FECHA_MOVIMIENTO
		/*WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO
		WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO*/
		
		End as [FECHA_ESTATUS]
	
	,A.OBSERVACIONES as CREDITOR_OBSERVATION
	,B.OBSERVACIONES as DEBITOR_OBSERVATION
	,A.OBS_COMITE as COMITE_OBSERVATION
	,B.CIRCUNSTANCIA_ID_DEU as DEBITOR_CIRCUMSTANCES
	,A.CIRCUNSTANCIA_ID_ACR as CREDITOR_CIRCUMSTANCES
	,TD.TTRANS_DESC as DEBITOR_TOT
	,TA.TTRANS_DESC as CREDITOR_TOT
	,TA.TTRANS_DESC as BASE
	,FM1.UUID as [FRACTURA_FOLIO]
	,FM2.UUID as [COMPLEMENTO_FOLIO]
	,FM3.UUID as [CANCELADA_FOLIO]
	,FM4.UUID as [CREDITO_FOLIO]
	,FM1.FECHA_MOVIMIENTO as [FECHA_FACTURA]
	,FE.FECHA_PAGO as [FECHA_PAGO]
	,FM2.FECHA_MOVIMIENTO as [FECHA_COMPLEMENTO_DE_PAGOS]
	,FM3.FECHA_MOVIMIENTO as [FECHA_CANCELADA]
	,FM4.FECHA_MOVIMIENTO as [FECHA_NOTA_DE_CREDITO]
	,FE.FECHA_ACEPTACION as ACEPTACION
	,FM2.FECHA_MOVIMIENTO as PAYMENT_DATE
	,FE.FECHA_PRIMER_RECHAZO as FIRST_REJECTION_DATE
	,A.IMPORTE_SALDO as COSTO
	,'OTRO'  as MOTIVO
	/*,(SELECT 
		U.NOMBRE || ' ' || U.AP_PATERNO || ' ' || U.AP_MATERNO 
		FROM dbo.BIT_ORDENES_DANO_MATERIAL A1
		LEFT OUTER JOIN USUARIOS U on A1.USUARIO_ID = U.USUARIO_ID 
		WHERE A1.FOLIO_ORDEN = A.FOLIO_ORDEN and A1.SINIESTRO_ID = A.SINIESTRO_ID 
		having A1.MOVTO_ID = MIN(A1.MOVTO_ID))as CAPTURED_BY
	,(SELECT 
		U.NOMBRE || ' ' || U.AP_PATERNO || ' ' || U.AP_MATERNO 
		FROM dbo.BIT_ORDENES_DANO_MATERIAL A1
		LEFT OUTER JOIN USUARIOS U on A1.USUARIO_ID = U.USUARIO_ID 
		WHERE A1.FOLIO_ORDEN = A.FOLIO_ORDEN and A1.SINIESTRO_ID = A.SINIESTRO_ID 
		having A1.MOVTO_ID = MAX(A1.MOVTO_ID)) as MODIFIED_BY*/
	  ,null as CAPTURED_BY
	  ,null as MODIFIED_BY
	,X.NOMBRE as [DEUDORA]
	,Y.NOMBRE as [ACREEDORA]
from dbo.BIT_ORDENES_DANO_MATERIAL A
LEFT OUTER JOIN dbo.BIT_SINIESTROS B on A.SINIESTRO_ID = B.SINIESTRO_ID
LEFT OUTER JOIN dbo.MUNICIPIOS M on B.MUNICIPIO_ID = M.MUNICIPIO_ID
LEFT OUTER JOIN dbo.ESTADOS E on M.ESTADO_ID = E.ESTADO_ID
LEFT OUTER JOIN dbo.V_TRANS_MAR_TIPO TD on B.TIPO_ID = TD.TIPO_ID
LEFT OUTER JOIN dbo.V_TRANS_MAR_TIPO TA on A.TIPO_ID = TA.TIPO_ID
INNER JOIN dbo.FAC_ORDEN_FACTURADA C on A.FOLIO_ORDEN = C.FOLIO and A.SINIESTRO_ID = C.ID_SINIESTRO and C.TIPO_ORDEN = 'D' and A.CAUSA_CANC_ID is not null
LEFT OUTER JOIN dbo.V_BIT_ORD_DM_FECHAS FE on C.FOLIO = FE.FOLIO_ORDEN and C.ID_SINIESTRO = FE.SINIESTRO_ID
LEFT OUTER JOIN dbo.FAC_MOVIMIENTO_FACTURACION D on C.ID_ORDEN_FACTURADA = D.ID_ORDEN_FACTURADA
LEFT OUTER JOIN COMPANIAS X ON B.CIA_DEUDORA = X.CIA_ID
LEFT OUTER JOIN COMPANIAS Y ON A.CIA_ACREEDORA = Y.CIA_ID	
LEFT OUTER JOIN V_FAC_REPORT_STATUS VFM1 on A.SINIESTRO_ID = VFM1.SINIESTRO_ID and A.FOLIO_ORDEN = VFM1.FOLIO_ORDEN and VFM1.Status = 2
LEFT OUTER JOIN FAC_MOVIMIENTO_FACTURACION FM1 on VFM1.MomentoID = FM1.ID_MOVIMIENTO_FACTURACION 
LEFT OUTER JOIN V_FAC_REPORT_STATUS VFM2 on A.SINIESTRO_ID = VFM2.SINIESTRO_ID and A.FOLIO_ORDEN = VFM2.FOLIO_ORDEN and VFM2.Status = 3
LEFT OUTER JOIN FAC_MOVIMIENTO_FACTURACION FM2 on VFM2.MomentoID = FM2.ID_MOVIMIENTO_FACTURACION 
LEFT OUTER JOIN V_FAC_REPORT_STATUS VFM3 on A.SINIESTRO_ID = VFM3.SINIESTRO_ID and A.FOLIO_ORDEN = VFM3.FOLIO_ORDEN and VFM3.Status = 4
LEFT OUTER JOIN FAC_MOVIMIENTO_FACTURACION FM3 on VFM3.MomentoID = FM3.ID_MOVIMIENTO_FACTURACION 
LEFT OUTER JOIN V_FAC_REPORT_STATUS VFM4 on A.SINIESTRO_ID = VFM4.SINIESTRO_ID and A.FOLIO_ORDEN = VFM4.FOLIO_ORDEN and VFM4.Status = 5
LEFT OUTER JOIN FAC_MOVIMIENTO_FACTURACION FM4 on VFM4.MomentoID = FM4.ID_MOVIMIENTO_FACTURACION;

CREATE OR REPLACE VIEW V_FAC_PROCESSMONITOR
AS
SELECT
	D.ID_MOVIMIENTO_ERROR as [MOVIMIENTO_ERROR_ID]
	,C.ID_ORDEN_FACTURADA as [FACTURADA_ID]
	,'D' as [TYPE]
	,A.TIPO_CAPTURA as CAPTURA
	,A.FOLIO_ORDEN as [FOLIO_ORDEN]
	,B.SINIESTRO_DEUDOR as [SIN_DEUDOR]
	,B.POLIZA as [POLIZA_DEUDOR]
	,A.SINIESTRO_ACREEDOR as [SIN_ACREEDORA]
	,A.POLIZA_ACREEDOR as [POLIZA_ACRREDORA]
	,A.SINIESTRO_CORRECTO as [SINIESTRO_CORRECTO]
	,D.MENSAJE_ERROR as [ERROR_MESSAGE]
	,D.CODIGO_ERROR as [ERROR_CODE]
	,D.REINTENTO as [REINTENTO]
	,D.FECHA_MOVIMIENTO as [ERROR_DATE]
	,E.DESCRIPCION as [ESTATUS]
	,X.NOMBRE as [DEUDORA]
	,Y.NOMBRE as [ACREEDORA]
FROM
	dbo.ORDENES_DANO_MATERIAL A
LEFT OUTER JOIN dbo.SINIESTROS B on A.SINIESTRO_ID = B.SINIESTRO_ID
LEFT OUTER JOIN dbo.FAC_ORDEN_FACTURADA C on A.FOLIO_ORDEN = C.FOLIO and A.SINIESTRO_ID = C.ID_SINIESTRO and C.TIPO_ORDEN = 'D'
INNER JOIN dbo.FAC_MOVIMIENTO_ERROR D on C.ID_ORDEN_FACTURADA = D.ID_ORDEN_FACTURADA
LEFT OUTER JOIN dbo.FAC_ESTATUS_FACTURACION E on D.ID_ESTATUS_FACTURACION = E.ID_ESTATUS_FACTURACION
LEFT OUTER JOIN COMPANIAS X ON C.CIA_DEUDORA = X.CIA_ID
LEFT OUTER JOIN COMPANIAS Y ON C.CIA_ACREEDORA = Y.CIA_ID
UNION
SELECT
	D.ID_MOVIMIENTO_ERROR as [MOVIMIENTO_ERROR_ID]
	,C.ID_ORDEN_FACTURADA as [FACTURADA_ID]
	,'G' as [TYPE]
	,A.TIPO_CAPTURA as CAPTURA
	,A.FOLIO_ORDEN as [FOLIO_ORDEN]
	,B.SINIESTRO_DEUDOR as [SIN_DEUDOR]
	,B.POLIZA as [POLIZA_DEUDOR]
	,A.SINIESTRO_ACREEDOR as [SIN_ACREEDORA]
	,A.POLIZA_ACREEDOR as [POLIZA_ACRREDORA]
	,A.SINIESTRO_CORRECTO as [SINIESTRO_CORRECTO]
	,D.MENSAJE_ERROR as [ERROR_MESSAGE]
	,D.CODIGO_ERROR as [ERROR_CODE]
	,D.REINTENTO as [REINTENTO]
	,D.FECHA_MOVIMIENTO as [ERROR_DATE]
	,E.DESCRIPCION as [ESTATUS]
	,X.NOMBRE as [DEUDORA]
	,Y.NOMBRE as [ACREEDORA]
FROM
	dbo.ORDENES_GASTO_MEDICO A
LEFT OUTER JOIN dbo.SINIESTROS B on A.SINIESTRO_ID = B.SINIESTRO_ID
LEFT OUTER JOIN dbo.FAC_ORDEN_FACTURADA C on A.FOLIO_ORDEN = C.FOLIO and A.SINIESTRO_ID = C.ID_SINIESTRO and C.TIPO_ORDEN = 'G'
INNER JOIN dbo.FAC_MOVIMIENTO_ERROR D on C.ID_ORDEN_FACTURADA = D.ID_ORDEN_FACTURADA
LEFT OUTER JOIN dbo.FAC_ESTATUS_FACTURACION E on D.ID_ESTATUS_FACTURACION = E.ID_ESTATUS_FACTURACION
LEFT OUTER JOIN COMPANIAS X ON C.CIA_DEUDORA = X.CIA_ID
LEFT OUTER JOIN COMPANIAS Y ON C.CIA_ACREEDORA = Y.CIA_ID;

CREATE OR REPLACE VIEW V_FAC_PR_GASTO
AS
SELECT DISTINCT
	C.ID_ORDEN_FACTURADA as [FACTURADA_ID]
	,'G' as [TYPE]
	,A.TIPO_CAPTURA as CAPTURA
	,A.FOLIO_ORDEN as [FOLIO_ORDEN]
	,B.SINIESTRO_DEUDOR as [SIN_DEUDOR]
--	,B.POLIZA as [POLIZA_DEUDOR]
	,A.SINIESTRO_ACREEDOR as [SIN_ACREEDORA]
--    ,A.POLIZA_ACREEDOR as [POLIZA_ACRREDORA]
	,A.SINIESTRO_CORRECTO as [CORRECT_EVENT]
	
,(SELECT SUM(SA.IMPORTE_SANCION)
                        FROM dbo.FAC_ORDEN_FACTURADA C1
						LEFT OUTER JOIN dbo.SANCIONES SA on C1.ID_SINIESTRO = SA.SINIESTRO_ID and C1.FOLIO = SA.FOLIO_ORDEN and SA.TIPO_ORDEN = 'D'
						where C1.ID_ORDEN_FACTURADA = C.ID_ORDEN_FACTURADA
						group by C1.ID_SINIESTRO,C1.FOLIO) as [SANCION]
	,A.DIAS_TRANSC as DAYS
	,A.FECHA_CAPTURA as REGISTRO
	,A.FECHA_EXP as EXPEDITION
	,B.FECHA_SINIESTRO as EVENT_FOLIO
	,E.DESCRIPCION as STATE
	,M.DESCRIPCION as LOCATION
	,CASE
	
		WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then 'CANCELACION'
		WHEN ISNULL(FM2.FECHA_MOVIMIENTO,'') <> '' then 'NOTA_CREDITO'
		WHEN ISNULL(FM3.FECHA_MOVIMIENTO,'') <> '' then 'COMPLEMENTO'
		WHEN ISNULL(FM1.FECHA_MOVIMIENTO,'') <> '' then 'FACTURA'
		/*WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO
		WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO*/
		
		End as [ULTIMO_STATUS]
	,CASE
		WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO
		WHEN ISNULL(FM2.FECHA_MOVIMIENTO,'') <> '' then FM2.FECHA_MOVIMIENTO
		WHEN ISNULL(FM3.FECHA_MOVIMIENTO,'') <> '' then FM3.FECHA_MOVIMIENTO
		WHEN ISNULL(FM1.FECHA_MOVIMIENTO,'') <> '' then FM1.FECHA_MOVIMIENTO
		/*WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO
		WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO*/
		
		End as [FECHA_ESTATUS]
	
	,A.OBSERVACIONES as CREDITOR_OBSERVATION
	,B.OBSERVACIONES as DEBITOR_OBSERVATION
	,A.OBS_COMITE as COMITE_OBSERVATION
	,B.CIRCUNSTANCIA_ID_DEU as DEBITOR_CIRCUMSTANCES
	,A.CIRCUNSTANCIA_ID_ACR as CREDITOR_CIRCUMSTANCES
	,null as DEBITOR_TOT
	,null as CREDITOR_TOT
	,null as BASE
	,FM1.UUID as [FRACTURA_FOLIO]
	,FM2.UUID as [COMPLEMENTO_FOLIO]
	,FM3.UUID as [CANCELADA_FOLIO]
	,FM4.UUID as [CREDITO_FOLIO]
	,FM1.FECHA_MOVIMIENTO as [FECHA_FACTURA]
	,FE.FECHA_PAGO as [FECHA_PAGO]
	,FM2.FECHA_MOVIMIENTO as [FECHA_COMPLEMENTO_DE_PAGOS]
	,FM3.FECHA_MOVIMIENTO as [FECHA_CANCELADA]
	,FM4.FECHA_MOVIMIENTO as [FECHA_NOTA_DE_CREDITO]
	,FE.FECHA_ACEPTACION as ACEPTACION
	,FM2.FECHA_MOVIMIENTO as PAYMENT_DATE
	,FE.FECHA_PRIMER_RECHAZO as FIRST_REJECTION_DATE
	,A.IMPORTE_SALDO as COSTO
	,MR.DESCRIPCION  as MOTIVO
	,(SELECT 
		U.NOMBRE || ' ' || U.AP_PATERNO || ' ' || U.AP_MATERNO 
		FROM dbo.ORDENES_GASTO_MEDICO A1
		LEFT OUTER JOIN USUARIOS U on A1.USUARIO_ID = U.USUARIO_ID 
		WHERE A1.FOLIO_ORDEN = A.FOLIO_ORDEN and A1.SINIESTRO_ID = A.SINIESTRO_ID )as CAPTURED_BY
	,(SELECT 
		U.NOMBRE || ' ' || U.AP_PATERNO || ' ' || U.AP_MATERNO 
		FROM dbo.ORDENES_GASTO_MEDICO A1
		LEFT OUTER JOIN USUARIOS U on A1.USUARIO_ID = U.USUARIO_ID 
		WHERE A1.FOLIO_ORDEN = A.FOLIO_ORDEN and A1.SINIESTRO_ID = A.SINIESTRO_ID ) as MODIFIED_BY
	,X.NOMBRE as [DEUDORA]
	,Y.NOMBRE as [ACREEDORA]
from dbo.ORDENES_GASTO_MEDICO A
LEFT OUTER JOIN dbo.SINIESTROS B on A.SINIESTRO_ID = B.SINIESTRO_ID
LEFT OUTER JOIN dbo.MUNICIPIOS M on B.MUNICIPIO_ID = M.MUNICIPIO_ID
LEFT OUTER JOIN dbo.ESTADOS E on M.ESTADO_ID = E.ESTADO_ID
--LEFT OUTER JOIN dbo.V_TRANS_MAR_TIPO TD on B.TIPO_ID = TD.TIPO_ID
--LEFT OUTER JOIN dbo.V_TRANS_MAR_TIPO TA on A.TIPO_ID = TA.TIPO_ID
INNER JOIN dbo.FAC_ORDEN_FACTURADA C on A.FOLIO_ORDEN = C.FOLIO and A.SINIESTRO_ID = C.ID_SINIESTRO and C.TIPO_ORDEN = 'G'
LEFT OUTER JOIN dbo.V_BIT_ORD_DM_FECHAS FE on C.FOLIO = FE.FOLIO_ORDEN and C.ID_SINIESTRO = FE.SINIESTRO_ID
LEFT OUTER JOIN dbo.FAC_MOVIMIENTO_FACTURACION D on C.ID_ORDEN_FACTURADA = D.ID_ORDEN_FACTURADA
LEFT OUTER JOIN COMPANIAS X ON B.CIA_DEUDORA = X.CIA_ID
LEFT OUTER JOIN COMPANIAS Y ON A.CIA_ACREEDORA = Y.CIA_ID	
LEFT OUTER JOIN V_FAC_REPORT_STATUS VFM1 on A.SINIESTRO_ID = VFM1.SINIESTRO_ID and A.FOLIO_ORDEN = VFM1.FOLIO_ORDEN and VFM1.Status = 2
LEFT OUTER JOIN FAC_MOVIMIENTO_FACTURACION FM1 on VFM1.MomentoID = FM1.ID_MOVIMIENTO_FACTURACION 
LEFT OUTER JOIN V_FAC_REPORT_STATUS VFM2 on A.SINIESTRO_ID = VFM2.SINIESTRO_ID and A.FOLIO_ORDEN = VFM2.FOLIO_ORDEN and VFM2.Status = 3
LEFT OUTER JOIN FAC_MOVIMIENTO_FACTURACION FM2 on VFM2.MomentoID = FM2.ID_MOVIMIENTO_FACTURACION 
LEFT OUTER JOIN V_FAC_REPORT_STATUS VFM3 on A.SINIESTRO_ID = VFM3.SINIESTRO_ID and A.FOLIO_ORDEN = VFM3.FOLIO_ORDEN and VFM3.Status = 4
LEFT OUTER JOIN FAC_MOVIMIENTO_FACTURACION FM3 on VFM3.MomentoID = FM3.ID_MOVIMIENTO_FACTURACION 
LEFT OUTER JOIN V_FAC_REPORT_STATUS VFM4 on A.SINIESTRO_ID = VFM4.SINIESTRO_ID and A.FOLIO_ORDEN = VFM4.FOLIO_ORDEN and VFM4.Status = 5
LEFT OUTER JOIN FAC_MOVIMIENTO_FACTURACION FM4 on VFM4.MomentoID = FM4.ID_MOVIMIENTO_FACTURACION
LEFT OUTER JOIN MOTIVO_RECHAZO MR on A.MOTIVO_ID = MR.MOTIVO_ID
UNION
SELECT DISTINCT
	C.ID_ORDEN_FACTURADA as [FACTURADA_ID]
	,'G' as [TYPE]
	,A.TIPO_CAPTURA as CAPTURA
	,A.FOLIO_ORDEN as [FOLIO_ORDEN]
	,B.SINIESTRO_DEUDOR as [SIN_DEUDOR]
--	,B.POLIZA as [POLIZA_DEUDOR]
	,A.SINIESTRO_ACREEDOR as [SIN_ACREEDORA]
--    ,A.POLIZA_ACREEDOR as [POLIZA_ACRREDORA]
	,A.SINIESTRO_CORRECTO as [CORRECT_EVENT]
	
,(SELECT SUM(SA.IMPORTE_SANCION)
                        FROM dbo.FAC_ORDEN_FACTURADA C1
						LEFT OUTER JOIN dbo.SANCIONES SA on C1.ID_SINIESTRO = SA.SINIESTRO_ID and C1.FOLIO = SA.FOLIO_ORDEN and SA.TIPO_ORDEN = 'D'
						where C1.ID_ORDEN_FACTURADA = C.ID_ORDEN_FACTURADA
						group by C1.ID_SINIESTRO,C1.FOLIO) as [SANCION]
	,A.DIAS_TRANSC as DAYS
	,A.FECHA_CAPTURA as REGISTRO
	,A.FECHA_EXP as EXPEDITION
	,B.FECHA_SINIESTRO as EVENT_FOLIO
	,E.DESCRIPCION as STATE
	,M.DESCRIPCION as LOCATION
	,CASE
	
		WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then 'CANCELACION'
		WHEN ISNULL(FM2.FECHA_MOVIMIENTO,'') <> '' then 'NOTA_CREDITO'
		WHEN ISNULL(FM3.FECHA_MOVIMIENTO,'') <> '' then 'COMPLEMENTO'
		WHEN ISNULL(FM1.FECHA_MOVIMIENTO,'') <> '' then 'FACTURA'
		/*WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO
		WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO*/
		
		End as [ULTIMO_STATUS]
	,CASE
		WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO
		WHEN ISNULL(FM2.FECHA_MOVIMIENTO,'') <> '' then FM2.FECHA_MOVIMIENTO
		WHEN ISNULL(FM3.FECHA_MOVIMIENTO,'') <> '' then FM3.FECHA_MOVIMIENTO
		WHEN ISNULL(FM1.FECHA_MOVIMIENTO,'') <> '' then FM1.FECHA_MOVIMIENTO
		/*WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO
		WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO*/
		
		End as [FECHA_ESTATUS]
	
	,A.OBSERVACIONES as CREDITOR_OBSERVATION
	,B.OBSERVACIONES as DEBITOR_OBSERVATION
	,A.OBS_COMITE as COMITE_OBSERVATION
	,B.CIRCUNSTANCIA_ID_DEU as DEBITOR_CIRCUMSTANCES
	,A.CIRCUNSTANCIA_ID_ACR as CREDITOR_CIRCUMSTANCES
	,null as DEBITOR_TOT
	,null as CREDITOR_TOT
	,null as BASE
	,FM1.UUID as [FRACTURA_FOLIO]
	,FM2.UUID as [COMPLEMENTO_FOLIO]
	,FM3.UUID as [CANCELADA_FOLIO]
	,FM4.UUID as [CREDITO_FOLIO]
	,FM1.FECHA_MOVIMIENTO as [FECHA_FACTURA]
	,FE.FECHA_PAGO as [FECHA_PAGO]
	,FM2.FECHA_MOVIMIENTO as [FECHA_COMPLEMENTO_DE_PAGOS]
	,FM3.FECHA_MOVIMIENTO as [FECHA_CANCELADA]
	,FM4.FECHA_MOVIMIENTO as [FECHA_NOTA_DE_CREDITO]
	,FE.FECHA_ACEPTACION as ACEPTACION
	,FM2.FECHA_MOVIMIENTO as PAYMENT_DATE
	,FE.FECHA_PRIMER_RECHAZO as FIRST_REJECTION_DATE
	,A.IMPORTE_SALDO as COSTO
	,'OTRO'  as MOTIVO
	/*,(SELECT 
		U.NOMBRE || ' ' || U.AP_PATERNO || ' ' || U.AP_MATERNO 
		FROM dbo.BIT_ORDENES_DANO_MATERIAL A1
		LEFT OUTER JOIN USUARIOS U on A1.USUARIO_ID = U.USUARIO_ID 
		WHERE A1.FOLIO_ORDEN = A.FOLIO_ORDEN and A1.SINIESTRO_ID = A.SINIESTRO_ID 
		having A1.MOVTO_ID = MIN(A1.MOVTO_ID))as CAPTURED_BY
	,(SELECT 
		U.NOMBRE || ' ' || U.AP_PATERNO || ' ' || U.AP_MATERNO 
		FROM dbo.BIT_ORDENES_DANO_MATERIAL A1
		LEFT OUTER JOIN USUARIOS U on A1.USUARIO_ID = U.USUARIO_ID 
		WHERE A1.FOLIO_ORDEN = A.FOLIO_ORDEN and A1.SINIESTRO_ID = A.SINIESTRO_ID 
		having A1.MOVTO_ID = MAX(A1.MOVTO_ID)) as MODIFIED_BY*/
	  ,null as CAPTURED_BY
	  ,null as MODIFIED_BY
	,X.NOMBRE as [DEUDORA]
	,Y.NOMBRE as [ACREEDORA]
from dbo.BIT_ORDENES_GASTO_MEDICO A
LEFT OUTER JOIN dbo.BIT_SINIESTROS B on A.SINIESTRO_ID = B.SINIESTRO_ID
LEFT OUTER JOIN dbo.MUNICIPIOS M on B.MUNICIPIO_ID = M.MUNICIPIO_ID
LEFT OUTER JOIN dbo.ESTADOS E on M.ESTADO_ID = E.ESTADO_ID
--LEFT OUTER JOIN dbo.V_TRANS_MAR_TIPO TD on B.TIPO_ID = TD.TIPO_ID
--LEFT OUTER JOIN dbo.V_TRANS_MAR_TIPO TA on A.TIPO_ID = TA.TIPO_ID
INNER JOIN dbo.FAC_ORDEN_FACTURADA C on A.FOLIO_ORDEN = C.FOLIO and A.SINIESTRO_ID = C.ID_SINIESTRO and C.TIPO_ORDEN = 'G' and A.CAUSA_CANC_ID is not null
LEFT OUTER JOIN dbo.V_BIT_ORD_DM_FECHAS FE on C.FOLIO = FE.FOLIO_ORDEN and C.ID_SINIESTRO = FE.SINIESTRO_ID
LEFT OUTER JOIN dbo.FAC_MOVIMIENTO_FACTURACION D on C.ID_ORDEN_FACTURADA = D.ID_ORDEN_FACTURADA
LEFT OUTER JOIN COMPANIAS X ON B.CIA_DEUDORA = X.CIA_ID
LEFT OUTER JOIN COMPANIAS Y ON A.CIA_ACREEDORA = Y.CIA_ID	
LEFT OUTER JOIN V_FAC_REPORT_STATUS VFM1 on A.SINIESTRO_ID = VFM1.SINIESTRO_ID and A.FOLIO_ORDEN = VFM1.FOLIO_ORDEN and VFM1.Status = 2
LEFT OUTER JOIN FAC_MOVIMIENTO_FACTURACION FM1 on VFM1.MomentoID = FM1.ID_MOVIMIENTO_FACTURACION 
LEFT OUTER JOIN V_FAC_REPORT_STATUS VFM2 on A.SINIESTRO_ID = VFM2.SINIESTRO_ID and A.FOLIO_ORDEN = VFM2.FOLIO_ORDEN and VFM2.Status = 3
LEFT OUTER JOIN FAC_MOVIMIENTO_FACTURACION FM2 on VFM2.MomentoID = FM2.ID_MOVIMIENTO_FACTURACION 
LEFT OUTER JOIN V_FAC_REPORT_STATUS VFM3 on A.SINIESTRO_ID = VFM3.SINIESTRO_ID and A.FOLIO_ORDEN = VFM3.FOLIO_ORDEN and VFM3.Status = 4
LEFT OUTER JOIN FAC_MOVIMIENTO_FACTURACION FM3 on VFM3.MomentoID = FM3.ID_MOVIMIENTO_FACTURACION 
LEFT OUTER JOIN V_FAC_REPORT_STATUS VFM4 on A.SINIESTRO_ID = VFM4.SINIESTRO_ID and A.FOLIO_ORDEN = VFM4.FOLIO_ORDEN and VFM4.Status = 5
LEFT OUTER JOIN FAC_MOVIMIENTO_FACTURACION FM4 on VFM4.MomentoID = FM4.ID_MOVIMIENTO_FACTURACION;

CREATE OR REPLACE VIEW V_FAC_REPORT
AS
SELECT DISTINCT
	C.ID_ORDEN_FACTURADA as [FACTURADA_ID]
	,'D' as [TYPE]
	,A.TIPO_CAPTURA as CAPTURA
	,A.FOLIO_ORDEN as [FOLIO_ORDEN]
	,B.SINIESTRO_DEUDOR as [SIN_DEUDOR]
	,B.POLIZA as [POLIZA_DEUDOR]
	,A.SINIESTRO_ACREEDOR as [SIN_ACREEDORA]
	,A.POLIZA_ACREEDOR as [POLIZA_ACRREDORA]
	,A.SINIESTRO_CORRECTO as [SINIESTRO_CORRECTO]
	,A.FECHA_CAPTURA as REGISTRO
	,R.FECHA_ESTATUS_SIPAC as ACEPTACION
	,FM1.FECHA_MOVIMIENTO as [FECHA_FACTURA]
	,Q.FECHA_ESTATUS_SIPAC as [FECHA_PAGO]
	,FM3.FECHA_MOVIMIENTO as [FECHA_COMPLEMENTO_DE_PAGOS]
	,FM4.FECHA_MOVIMIENTO as [FECHA_CANCELADA]
	,FM2.FECHA_MOVIMIENTO as [FECHA_NOTA_DE_CREDITO]
	,FM1.UUID as [FRACTURA_FOLIO]
	,FM3.UUID as [COMPLEMENTO_FOLIO]
	,FM4.UUID as [CANCELADA_FOLIO]
	,FM2.UUID as [CREDITO_FOLIO]
	,A.IMPORTE_SALDO as COSTO
	,CASE
		WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then 'CANCELACION'
		WHEN ISNULL(FM2.FECHA_MOVIMIENTO,'') <> '' then 'NOTA_CREDITO'
		WHEN ISNULL(FM3.FECHA_MOVIMIENTO,'') <> '' then 'COMPLEMENTO'
		WHEN ISNULL(FM1.FECHA_MOVIMIENTO,'') <> '' then 'FACTURA'
		/*WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO
		WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO*/
		
		End as [ULTIMO_STATUS]
	,CASE
		WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO
		WHEN ISNULL(FM2.FECHA_MOVIMIENTO,'') <> '' then FM2.FECHA_MOVIMIENTO
		WHEN ISNULL(FM3.FECHA_MOVIMIENTO,'') <> '' then FM3.FECHA_MOVIMIENTO
		WHEN ISNULL(FM1.FECHA_MOVIMIENTO,'') <> '' then FM1.FECHA_MOVIMIENTO
		/*WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO
		WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO*/
		
		End as [FECHA_ESTATUS]
	,'FACTURA' as USUARIO
	,X.NOMBRE as [DEUDORA]
	,Y.NOMBRE as [ACREEDORA]
	,FM1.CFDI_XML as FACTURA_XML
	,FM1.CFDI_PDF as FACTURA_PDF
	,FM2.CFDI_XML as CREDITO_XML
	,FM2.CFDI_PDF as CREDITO_PDF
	,FM3.CFDI_XML as COMPLEMENTO_XML
	,FM3.CFDI_PDF as COMPLEMENTO_PDF
	,FM4.CFDI_XML as CANCELACION_XML 
	,FM4.CFDI_PDF as CANCELACION_PDF
from dbo.ORDENES_DANO_MATERIAL A
LEFT OUTER JOIN dbo.SINIESTROS B on A.SINIESTRO_ID = B.SINIESTRO_ID
INNER JOIN dbo.FAC_ORDEN_FACTURADA C on A.FOLIO_ORDEN = C.FOLIO and A.SINIESTRO_ID = C.ID_SINIESTRO and C.TIPO_ORDEN = 'D'
LEFT OUTER JOIN dbo.FAC_MOVIMIENTO_FACTURACION D on C.ID_ORDEN_FACTURADA = D.ID_ORDEN_FACTURADA
LEFT OUTER JOIN COMPANIAS X ON B.CIA_DEUDORA = X.CIA_ID
LEFT OUTER JOIN COMPANIAS Y ON A.CIA_ACREEDORA = Y.CIA_ID	
LEFT OUTER JOIN V_FAC_REPORT_STATUS VFM1 on A.SINIESTRO_ID = VFM1.SINIESTRO_ID and A.FOLIO_ORDEN = VFM1.FOLIO_ORDEN and VFM1.Status = 2
LEFT OUTER JOIN FAC_MOVIMIENTO_FACTURACION FM1 on VFM1.MomentoID = FM1.ID_MOVIMIENTO_FACTURACION 
LEFT OUTER JOIN V_FAC_REPORT_STATUS VFM2 on A.SINIESTRO_ID = VFM2.SINIESTRO_ID and A.FOLIO_ORDEN = VFM2.FOLIO_ORDEN and VFM2.Status = 3
LEFT OUTER JOIN FAC_MOVIMIENTO_FACTURACION FM2 on VFM2.MomentoID = FM2.ID_MOVIMIENTO_FACTURACION 
LEFT OUTER JOIN V_FAC_REPORT_STATUS VFM3 on A.SINIESTRO_ID = VFM3.SINIESTRO_ID and A.FOLIO_ORDEN = VFM3.FOLIO_ORDEN and VFM3.Status = 4
LEFT OUTER JOIN FAC_MOVIMIENTO_FACTURACION FM3 on VFM3.MomentoID = FM3.ID_MOVIMIENTO_FACTURACION 
LEFT OUTER JOIN V_FAC_REPORT_STATUS VFM4 on A.SINIESTRO_ID = VFM4.SINIESTRO_ID and A.FOLIO_ORDEN = VFM4.FOLIO_ORDEN and VFM4.Status = 5
LEFT OUTER JOIN FAC_MOVIMIENTO_FACTURACION FM4 on VFM4.MomentoID = FM4.ID_MOVIMIENTO_FACTURACION
LEFT OUTER JOIN dbo.FAC_ORDEN_FACTURADA R on A.FOLIO_ORDEN = R.FOLIO and A.SINIESTRO_ID = R.ID_SINIESTRO and R.TIPO_ORDEN = 'D' and R.ESTATUS_SIPAC in('A')
LEFT OUTER JOIN dbo.FAC_ORDEN_FACTURADA Q on A.FOLIO_ORDEN = Q.FOLIO and A.SINIESTRO_ID = Q.ID_SINIESTRO and Q.TIPO_ORDEN = 'D' and R.ESTATUS_SIPAC in('Q')
UNION
SELECT DISTINCT
	C.ID_ORDEN_FACTURADA as [FACTURADA_ID]
	,'D' as [TYPE]
	,A.TIPO_CAPTURA as CAPTURA
	,A.FOLIO_ORDEN as [FOLIO_ORDEN]
	,B.SINIESTRO_DEUDOR as [SIN_DEUDOR]
	,B.POLIZA as [POLIZA_DEUDOR]
	,A.SINIESTRO_ACREEDOR as [SIN_ACREEDORA]
	,A.POLIZA_ACREEDOR as [POLIZA_ACRREDORA]
	,A.SINIESTRO_CORRECTO as [SINIESTRO_CORRECTO]
	,A.FECHA_CAPTURA as REGISTRO
	,R.FECHA_ESTATUS_SIPAC as ACEPTACION
	,FM1.FECHA_MOVIMIENTO as [FECHA_FACTURA]
	,Q.FECHA_ESTATUS_SIPAC as [FECHA_PAGO]
	,FM3.FECHA_MOVIMIENTO as [FECHA_COMPLEMENTO_DE_PAGOS]
	,FM4.FECHA_MOVIMIENTO as [FECHA_CANCELADA]
	,FM2.FECHA_MOVIMIENTO as [FECHA_NOTA_DE_CREDITO]
	,FM1.UUID as [FRACTURA_FOLIO]
	,FM3.UUID as [COMPLEMENTO_FOLIO]
	,FM4.UUID as [CANCELADA_FOLIO]
	,FM2.UUID as [CREDITO_FOLIO]
	,A.IMPORTE_SALDO as COSTO
	,CASE
		WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then 'CANCELACION'
		WHEN ISNULL(FM2.FECHA_MOVIMIENTO,'') <> '' then 'NOTA_CREDITO'
		WHEN ISNULL(FM3.FECHA_MOVIMIENTO,'') <> '' then 'COMPLEMENTO'
		WHEN ISNULL(FM1.FECHA_MOVIMIENTO,'') <> '' then 'FACTURA'
		/*WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO
		WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO*/
		
		End as [ULTIMO_STATUS]
	,CASE
		WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO
		WHEN ISNULL(FM2.FECHA_MOVIMIENTO,'') <> '' then FM2.FECHA_MOVIMIENTO
		WHEN ISNULL(FM3.FECHA_MOVIMIENTO,'') <> '' then FM3.FECHA_MOVIMIENTO
		WHEN ISNULL(FM1.FECHA_MOVIMIENTO,'') <> '' then FM1.FECHA_MOVIMIENTO
		/*WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO
		WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO*/
		
		End as [FECHA_ESTATUS]
	,'FACTURA' as USUARIO
	,X.NOMBRE as [DEUDORA]
	,Y.NOMBRE as [ACREEDORA]
	,FM1.CFDI_XML as FACTURA_XML
	,FM1.CFDI_PDF as FACTURA_PDF
	,FM2.CFDI_XML as CREDITO_XML
	,FM2.CFDI_PDF as CREDITO_PDF
	,FM3.CFDI_XML as COMPLEMENTO_XML
	,FM3.CFDI_PDF as COMPLEMENTO_PDF
	,FM4.CFDI_XML as CANCELACION_XML 
	,FM4.CFDI_PDF as CANCELACION_PDF
from dbo.BIT_ORDENES_DANO_MATERIAL A (INDEX PK_BIT_ORDENES_DANO_MATERIAL)
LEFT OUTER JOIN dbo.BIT_SINIESTROS B on A.SINIESTRO_ID = B.SINIESTRO_ID
INNER JOIN dbo.FAC_ORDEN_FACTURADA C on A.FOLIO_ORDEN = C.FOLIO and A.SINIESTRO_ID = C.ID_SINIESTRO and C.TIPO_ORDEN = 'D' and A.CAUSA_CANC_ID is not null
LEFT OUTER JOIN dbo.FAC_MOVIMIENTO_FACTURACION D on C.ID_ORDEN_FACTURADA = D.ID_ORDEN_FACTURADA
LEFT OUTER JOIN COMPANIAS X ON B.CIA_DEUDORA = X.CIA_ID
LEFT OUTER JOIN COMPANIAS Y ON A.CIA_ACREEDORA = Y.CIA_ID	
LEFT OUTER JOIN V_FAC_REPORT_STATUS VFM1 on A.SINIESTRO_ID = VFM1.SINIESTRO_ID and A.FOLIO_ORDEN = VFM1.FOLIO_ORDEN and VFM1.Status = 2
LEFT OUTER JOIN FAC_MOVIMIENTO_FACTURACION FM1 on VFM1.MomentoID = FM1.ID_MOVIMIENTO_FACTURACION 
LEFT OUTER JOIN V_FAC_REPORT_STATUS VFM2 on A.SINIESTRO_ID = VFM2.SINIESTRO_ID and A.FOLIO_ORDEN = VFM2.FOLIO_ORDEN and VFM2.Status = 3
LEFT OUTER JOIN FAC_MOVIMIENTO_FACTURACION FM2 on VFM2.MomentoID = FM2.ID_MOVIMIENTO_FACTURACION 
LEFT OUTER JOIN V_FAC_REPORT_STATUS VFM3 on A.SINIESTRO_ID = VFM3.SINIESTRO_ID and A.FOLIO_ORDEN = VFM3.FOLIO_ORDEN and VFM3.Status = 4
LEFT OUTER JOIN FAC_MOVIMIENTO_FACTURACION FM3 on VFM3.MomentoID = FM3.ID_MOVIMIENTO_FACTURACION 
LEFT OUTER JOIN V_FAC_REPORT_STATUS VFM4 on A.SINIESTRO_ID = VFM4.SINIESTRO_ID and A.FOLIO_ORDEN = VFM4.FOLIO_ORDEN and VFM4.Status = 5
LEFT OUTER JOIN FAC_MOVIMIENTO_FACTURACION FM4 on VFM4.MomentoID = FM4.ID_MOVIMIENTO_FACTURACION
LEFT OUTER JOIN dbo.FAC_ORDEN_FACTURADA R on A.FOLIO_ORDEN = R.FOLIO and A.SINIESTRO_ID = R.ID_SINIESTRO and R.TIPO_ORDEN = 'D' and R.ESTATUS_SIPAC in('A')
LEFT OUTER JOIN dbo.FAC_ORDEN_FACTURADA Q on A.FOLIO_ORDEN = Q.FOLIO and A.SINIESTRO_ID = Q.ID_SINIESTRO and Q.TIPO_ORDEN = 'D' and R.ESTATUS_SIPAC in('Q');

CREATE OR REPLACE VIEW V_FAC_REPORT_GASTO
AS
SELECT DISTINCT
	C.ID_ORDEN_FACTURADA as [FACTURADA_ID]
	,'G' as [TYPE]
	,A.TIPO_CAPTURA as CAPTURA
	,A.FOLIO_ORDEN as [FOLIO_ORDEN]
	,B.SINIESTRO_DEUDOR as [SIN_DEUDOR]
	,B.POLIZA as [POLIZA_DEUDOR]
	,A.SINIESTRO_ACREEDOR as [SIN_ACREEDORA]
	,A.POLIZA_ACREEDOR as [POLIZA_ACRREDORA]
	,A.SINIESTRO_CORRECTO as [SINIESTRO_CORRECTO]
	,A.FECHA_CAPTURA as REGISTRO
	,R.FECHA_ESTATUS_SIPAC as ACEPTACION
	,FM1.FECHA_MOVIMIENTO as [FECHA_FACTURA]
	,Q.FECHA_ESTATUS_SIPAC as [FECHA_PAGO]
	,FM3.FECHA_MOVIMIENTO as [FECHA_COMPLEMENTO_DE_PAGOS]
	,FM4.FECHA_MOVIMIENTO as [FECHA_CANCELADA]
	,FM2.FECHA_MOVIMIENTO as [FECHA_NOTA_DE_CREDITO]
	,FM1.UUID as [FRACTURA_FOLIO]
	,FM3.UUID as [COMPLEMENTO_FOLIO]
	,FM4.UUID as [CANCELADA_FOLIO]
	,FM2.UUID as [CREDITO_FOLIO]
	,A.IMPORTE_SALDO as COSTO
	,CASE
		WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then 'CANCELACION'
		WHEN ISNULL(FM2.FECHA_MOVIMIENTO,'') <> '' then 'NOTA_CREDITO'
		WHEN ISNULL(FM3.FECHA_MOVIMIENTO,'') <> '' then 'COMPLEMENTO'
		WHEN ISNULL(FM1.FECHA_MOVIMIENTO,'') <> '' then 'FACTURA'
		/*WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO
		WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO*/
		
		End as [ULTIMO_STATUS]
	,CASE
		WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO
		WHEN ISNULL(FM2.FECHA_MOVIMIENTO,'') <> '' then FM2.FECHA_MOVIMIENTO
		WHEN ISNULL(FM3.FECHA_MOVIMIENTO,'') <> '' then FM3.FECHA_MOVIMIENTO
		WHEN ISNULL(FM1.FECHA_MOVIMIENTO,'') <> '' then FM1.FECHA_MOVIMIENTO
		/*WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO
		WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO*/
		
		End as [FECHA_ESTATUS]
	,'FACTURA' as USUARIO
	,X.NOMBRE as [DEUDORA]
	,Y.NOMBRE as [ACREEDORA]
	,FM1.CFDI_XML as FACTURA_XML
	,FM1.CFDI_PDF as FACTURA_PDF
	,FM2.CFDI_XML as CREDITO_XML
	,FM2.CFDI_PDF as CREDITO_PDF
	,FM3.CFDI_XML as COMPLEMENTO_XML
	,FM3.CFDI_PDF as COMPLEMENTO_PDF
	,FM4.CFDI_XML as CANCELACION_XML 
	,FM4.CFDI_PDF as CANCELACION_PDF
from dbo.ORDENES_GASTO_MEDICO A
LEFT OUTER JOIN dbo.SINIESTROS B on A.SINIESTRO_ID = B.SINIESTRO_ID
INNER JOIN dbo.FAC_ORDEN_FACTURADA C on A.FOLIO_ORDEN = C.FOLIO and A.SINIESTRO_ID = C.ID_SINIESTRO and C.TIPO_ORDEN = 'G'
LEFT OUTER JOIN dbo.FAC_MOVIMIENTO_FACTURACION D on C.ID_ORDEN_FACTURADA = D.ID_ORDEN_FACTURADA
LEFT OUTER JOIN COMPANIAS X ON B.CIA_DEUDORA = X.CIA_ID
LEFT OUTER JOIN COMPANIAS Y ON A.CIA_ACREEDORA = Y.CIA_ID	
LEFT OUTER JOIN V_FAC_REPORT_STATUS VFM1 on A.SINIESTRO_ID = VFM1.SINIESTRO_ID and A.FOLIO_ORDEN = VFM1.FOLIO_ORDEN and VFM1.Status = 2
LEFT OUTER JOIN FAC_MOVIMIENTO_FACTURACION FM1 on VFM1.MomentoID = FM1.ID_MOVIMIENTO_FACTURACION 
LEFT OUTER JOIN V_FAC_REPORT_STATUS VFM2 on A.SINIESTRO_ID = VFM2.SINIESTRO_ID and A.FOLIO_ORDEN = VFM2.FOLIO_ORDEN and VFM2.Status = 3
LEFT OUTER JOIN FAC_MOVIMIENTO_FACTURACION FM2 on VFM2.MomentoID = FM2.ID_MOVIMIENTO_FACTURACION 
LEFT OUTER JOIN V_FAC_REPORT_STATUS VFM3 on A.SINIESTRO_ID = VFM3.SINIESTRO_ID and A.FOLIO_ORDEN = VFM3.FOLIO_ORDEN and VFM3.Status = 4
LEFT OUTER JOIN FAC_MOVIMIENTO_FACTURACION FM3 on VFM3.MomentoID = FM3.ID_MOVIMIENTO_FACTURACION 
LEFT OUTER JOIN V_FAC_REPORT_STATUS VFM4 on A.SINIESTRO_ID = VFM4.SINIESTRO_ID and A.FOLIO_ORDEN = VFM4.FOLIO_ORDEN and VFM4.Status = 5
LEFT OUTER JOIN FAC_MOVIMIENTO_FACTURACION FM4 on VFM4.MomentoID = FM4.ID_MOVIMIENTO_FACTURACION
LEFT OUTER JOIN dbo.FAC_ORDEN_FACTURADA R on A.FOLIO_ORDEN = R.FOLIO and A.SINIESTRO_ID = R.ID_SINIESTRO and R.TIPO_ORDEN = 'D' and R.ESTATUS_SIPAC in('A')
LEFT OUTER JOIN dbo.FAC_ORDEN_FACTURADA Q on A.FOLIO_ORDEN = Q.FOLIO and A.SINIESTRO_ID = Q.ID_SINIESTRO and Q.TIPO_ORDEN = 'D' and R.ESTATUS_SIPAC in('Q')
UNION
SELECT DISTINCT
	C.ID_ORDEN_FACTURADA as [FACTURADA_ID]
	,'G' as [TYPE]
	,A.TIPO_CAPTURA as CAPTURA
	,A.FOLIO_ORDEN as [FOLIO_ORDEN]
	,B.SINIESTRO_DEUDOR as [SIN_DEUDOR]
	,B.POLIZA as [POLIZA_DEUDOR]
	,A.SINIESTRO_ACREEDOR as [SIN_ACREEDORA]
	,A.POLIZA_ACREEDOR as [POLIZA_ACRREDORA]
	,A.SINIESTRO_CORRECTO as [SINIESTRO_CORRECTO]
	,A.FECHA_CAPTURA as REGISTRO
	,R.FECHA_ESTATUS_SIPAC as ACEPTACION
	,FM1.FECHA_MOVIMIENTO as [FECHA_FACTURA]
	,Q.FECHA_ESTATUS_SIPAC as [FECHA_PAGO]
	,FM3.FECHA_MOVIMIENTO as [FECHA_COMPLEMENTO_DE_PAGOS]
	,FM4.FECHA_MOVIMIENTO as [FECHA_CANCELADA]
	,FM2.FECHA_MOVIMIENTO as [FECHA_NOTA_DE_CREDITO]
	,FM1.UUID as [FRACTURA_FOLIO]
	,FM3.UUID as [COMPLEMENTO_FOLIO]
	,FM4.UUID as [CANCELADA_FOLIO]
	,FM2.UUID as [CREDITO_FOLIO]
	,A.IMPORTE_SALDO as COSTO
	,CASE
		WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then 'CANCELACION'
		WHEN ISNULL(FM2.FECHA_MOVIMIENTO,'') <> '' then 'NOTA_CREDITO'
		WHEN ISNULL(FM3.FECHA_MOVIMIENTO,'') <> '' then 'COMPLEMENTO'
		WHEN ISNULL(FM1.FECHA_MOVIMIENTO,'') <> '' then 'FACTURA'
		/*WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO
		WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO*/
		
		End as [ULTIMO_STATUS]
	,CASE
		WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO
		WHEN ISNULL(FM2.FECHA_MOVIMIENTO,'') <> '' then FM2.FECHA_MOVIMIENTO
		WHEN ISNULL(FM3.FECHA_MOVIMIENTO,'') <> '' then FM3.FECHA_MOVIMIENTO
		WHEN ISNULL(FM1.FECHA_MOVIMIENTO,'') <> '' then FM1.FECHA_MOVIMIENTO
		/*WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO
		WHEN ISNULL(FM4.FECHA_MOVIMIENTO,'') <> '' then FM4.FECHA_MOVIMIENTO*/
		
		End as [FECHA_ESTATUS]
	,'FACTURA' as USUARIO
	,X.NOMBRE as [DEUDORA]
	,Y.NOMBRE as [ACREEDORA]
	,FM1.CFDI_XML as FACTURA_XML
	,FM1.CFDI_PDF as FACTURA_PDF
	,FM2.CFDI_XML as CREDITO_XML
	,FM2.CFDI_PDF as CREDITO_PDF
	,FM3.CFDI_XML as COMPLEMENTO_XML
	,FM3.CFDI_PDF as COMPLEMENTO_PDF
	,FM4.CFDI_XML as CANCELACION_XML 
	,FM4.CFDI_PDF as CANCELACION_PDF
from dbo.BIT_ORDENES_GASTO_MEDICO A
LEFT OUTER JOIN dbo.BIT_SINIESTROS B on A.SINIESTRO_ID = B.SINIESTRO_ID
INNER JOIN dbo.FAC_ORDEN_FACTURADA C on A.FOLIO_ORDEN = C.FOLIO and A.SINIESTRO_ID = C.ID_SINIESTRO and C.TIPO_ORDEN = 'G' and A.CAUSA_CANC_ID is not null
LEFT OUTER JOIN dbo.FAC_MOVIMIENTO_FACTURACION D on C.ID_ORDEN_FACTURADA = D.ID_ORDEN_FACTURADA
LEFT OUTER JOIN COMPANIAS X ON B.CIA_DEUDORA = X.CIA_ID
LEFT OUTER JOIN COMPANIAS Y ON A.CIA_ACREEDORA = Y.CIA_ID	
LEFT OUTER JOIN V_FAC_REPORT_STATUS VFM1 on A.SINIESTRO_ID = VFM1.SINIESTRO_ID and A.FOLIO_ORDEN = VFM1.FOLIO_ORDEN and VFM1.Status = 2
LEFT OUTER JOIN FAC_MOVIMIENTO_FACTURACION FM1 on VFM1.MomentoID = FM1.ID_MOVIMIENTO_FACTURACION 
LEFT OUTER JOIN V_FAC_REPORT_STATUS VFM2 on A.SINIESTRO_ID = VFM2.SINIESTRO_ID and A.FOLIO_ORDEN = VFM2.FOLIO_ORDEN and VFM2.Status = 3
LEFT OUTER JOIN FAC_MOVIMIENTO_FACTURACION FM2 on VFM2.MomentoID = FM2.ID_MOVIMIENTO_FACTURACION 
LEFT OUTER JOIN V_FAC_REPORT_STATUS VFM3 on A.SINIESTRO_ID = VFM3.SINIESTRO_ID and A.FOLIO_ORDEN = VFM3.FOLIO_ORDEN and VFM3.Status = 4
LEFT OUTER JOIN FAC_MOVIMIENTO_FACTURACION FM3 on VFM3.MomentoID = FM3.ID_MOVIMIENTO_FACTURACION 
LEFT OUTER JOIN V_FAC_REPORT_STATUS VFM4 on A.SINIESTRO_ID = VFM4.SINIESTRO_ID and A.FOLIO_ORDEN = VFM4.FOLIO_ORDEN and VFM4.Status = 5
LEFT OUTER JOIN FAC_MOVIMIENTO_FACTURACION FM4 on VFM4.MomentoID = FM4.ID_MOVIMIENTO_FACTURACION
LEFT OUTER JOIN dbo.FAC_ORDEN_FACTURADA R on A.FOLIO_ORDEN = R.FOLIO and A.SINIESTRO_ID = R.ID_SINIESTRO and R.TIPO_ORDEN = 'D' and R.ESTATUS_SIPAC in('A')
LEFT OUTER JOIN dbo.FAC_ORDEN_FACTURADA Q on A.FOLIO_ORDEN = Q.FOLIO and A.SINIESTRO_ID = Q.ID_SINIESTRO and Q.TIPO_ORDEN = 'D' and R.ESTATUS_SIPAC in('Q');

CREATE OR REPLACE VIEW V_FAC_REPORT_STATUS
AS
SELECT
	A.FOLIO_ORDEN
	,A.SINIESTRO_ID
	,Max(FM2.ID_MOVIMIENTO_FACTURACION) as [MomentoID]
	,FM2.ID_ESTATUS_FACTURACION as [Status]
from dbo.ORDENES_DANO_MATERIAL A
INNER JOIN dbo.FAC_ORDEN_FACTURADA C on A.FOLIO_ORDEN = C.FOLIO and A.SINIESTRO_ID = C.ID_SINIESTRO and C.TIPO_ORDEN = 'D'
LEFT OUTER JOIN FAC_MOVIMIENTO_FACTURACION FM2 ON C.ID_ORDEN_FACTURADA = FM2.ID_ORDEN_FACTURADA 
group by 	
A.FOLIO_ORDEN
	,A.SINIESTRO_ID
	,FM2.ID_ESTATUS_FACTURACION
UNION
SELECT
	A.FOLIO_ORDEN
	,A.SINIESTRO_ID
	,Max(FM2.ID_MOVIMIENTO_FACTURACION) as [MomentoID]
	,FM2.ID_ESTATUS_FACTURACION as [Status]
from dbo.ORDENES_GASTO_MEDICO A
INNER JOIN dbo.FAC_ORDEN_FACTURADA C on A.FOLIO_ORDEN = C.FOLIO and A.SINIESTRO_ID = C.ID_SINIESTRO and C.TIPO_ORDEN = 'G'
LEFT OUTER JOIN FAC_MOVIMIENTO_FACTURACION FM2 ON C.ID_ORDEN_FACTURADA = FM2.ID_ORDEN_FACTURADA 
group by 	
A.FOLIO_ORDEN
	,A.SINIESTRO_ID
	,FM2.ID_ESTATUS_FACTURACION
UNION
SELECT
	A.FOLIO_ORDEN
	,A.SINIESTRO_ID
	,Max(FM2.ID_MOVIMIENTO_FACTURACION) as [MomentoID]
	,FM2.ID_ESTATUS_FACTURACION as [Status]
from dbo.BIT_ORDENES_DANO_MATERIAL A
INNER JOIN dbo.FAC_ORDEN_FACTURADA C on A.FOLIO_ORDEN = C.FOLIO and A.SINIESTRO_ID = C.ID_SINIESTRO and C.TIPO_ORDEN = 'D' and A.CAUSA_CANC_ID is not null
LEFT OUTER JOIN FAC_MOVIMIENTO_FACTURACION FM2 ON C.ID_ORDEN_FACTURADA = FM2.ID_ORDEN_FACTURADA 
group by 	
A.FOLIO_ORDEN
	,A.SINIESTRO_ID
	,FM2.ID_ESTATUS_FACTURACION
UNION
SELECT
	A.FOLIO_ORDEN
	,A.SINIESTRO_ID
	,Max(FM2.ID_MOVIMIENTO_FACTURACION) as [MomentoID]
	,FM2.ID_ESTATUS_FACTURACION as [Status]
from dbo.BIT_ORDENES_GASTO_MEDICO A
INNER JOIN dbo.FAC_ORDEN_FACTURADA C on A.FOLIO_ORDEN = C.FOLIO and A.SINIESTRO_ID = C.ID_SINIESTRO and C.TIPO_ORDEN = 'G' and A.CAUSA_CANC_ID is not null
LEFT OUTER JOIN FAC_MOVIMIENTO_FACTURACION FM2 ON C.ID_ORDEN_FACTURADA = FM2.ID_ORDEN_FACTURADA 
group by 	
A.FOLIO_ORDEN
	,A.SINIESTRO_ID
	,FM2.ID_ESTATUS_FACTURACION;

CREATE or Replace VIEW V_FAC_SUMMARY_REPORT AS
Select 
A.ACREEDORA SOURCECOMPANY
,A.DEUDORA TransactionCompany
,'Credit' TransactionType
,A.TotalCost TotalCreditCost
,A.TotalCount TotalCreditCount
,0 TotalDebitCost
,0 TotalDebitCount
,A.TransactionDate
,A.ID_ESTATUS_FACTURACION
From sipac_fac.dbo.V_FAC_SUMMARY_REPORT_HELPER A
UNION
Select 
A.DEUDORA SOURCECOMPANY
,A.ACREEDORA TransactionCompany
,'Debit' TransactionType
,0 TotalCreditCost
,0 TotalCreditCount
,A.TotalCost TotalDebitCost
,A.TotalCount TotalDebitCount
,A.TransactionDate
,A.ID_ESTATUS_FACTURACION
From sipac_fac.dbo.V_FAC_SUMMARY_REPORT_HELPER A;

Create or Replace View V_FAC_SUMMARY_REPORT_HELPER AS
Select 
	B.NOMBRE ACREEDORA
	,SUM(A.IMPORTE_SALDO) TotalCost
	,D.NOMBRE DEUDORA
	,Convert(Date, F.FECHA_MOVIMIENTO) TransactionDate
	,F.ID_ESTATUS_FACTURACION
	,Count(*) TotalCount
from dbo.ORDENES_DANO_MATERIAL A
INNER JOIN dbo.COMPANIAS B on A.CIA_ACREEDORA = B.CIA_ID
INNER JOIN dbo.SINIESTROS C on A.SINIESTRO_ID = C.SINIESTRO_ID
INNER JOIN dbo.COMPANIAS D on C.CIA_DEUDORA = D.CIA_ID
Inner JOIN dbo.FAC_ORDEN_FACTURADA E on A.FOLIO_ORDEN = E.FOLIO and A.SINIESTRO_ID = E.ID_SINIESTRO
INNER JOIN dbo.FAC_MOVIMIENTO_FACTURACION F on E.ID_ORDEN_FACTURADA = F.ID_ORDEN_FACTURADA
WHERE Convert(Date, F.FECHA_MOVIMIENTO) > dateadd(day,-2,convert(char(10), getdate(), 23)) and Convert(Date, F.FECHA_MOVIMIENTO) < getdate()

Group by 
	B.NOMBRE
	,D.NOMBRE
	,Convert(Date, F.FECHA_MOVIMIENTO)
	,F.ID_ESTATUS_FACTURACION;

CREATE OR REPLACE VIEW V_FAC_USUARIO
AS
SELECT 
	A.ID_USUARIO as [ID_USUARIO]
	,B.NOMBRE as [COMPANIA]
	,A.NOMBRE as [USUARIO]
	,A.APELLIDO_PATERNO as [APELLIDO_PATERNO]
	,A.APELLIDO_MATERNO as [APELLIDO_MATERNO]
	,A.NOMBRE_USUARIO as [NOMBRE_USUARIO]
	,A.CORREO_ELECTRONICO as [CORREO_ELECTRONICO]
	,A.TELEFONO as [TELEFONO]
	,C.DESCRIPCION as [ROL]
	,A.ACTIVO as [ACTIVO]
	,A.NOTIFICAR_EMAIL as [NOTIFICAR_EMAIL]
FROM 
	FAC_USUARIO A
LEFT OUTER JOIN COMPANIAS B ON A.ID_COMPANIA = B.CIA_ID
LEFT OUTER JOIN FAC_ROL C ON A.ID_ROL = C.ID_ROL;
